

version: '3'
networks:
  lbs.net:
    driver: bridge
services:

# http://api.commande.local:19080

  api.commande:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.commande.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - 19080:80
      - 19043:443
    volumes:
      - ./lbs_commande_service/api:/var/www/api
      - ./lbs_commande_service/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - lbs.net
    links:
      - mysql.commande:command
      - api.catalogue:api.catalogue.local

#https://api.catalogue.local:19180

  api.catalogue:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.catalogue.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - 19180:80
      - 19143:443
    volumes:
      - ./lbs_catalogue_service/api:/var/www/api
      - ./lbs_catalogue_service/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - lbs.net
    links:
#      - mongo.cat:dbcat
      - mysql.catalogue:catalogue


# http://api.fidelisation.local:19280

  api.fidelisation:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.fidelisation.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - 19280:80
      - 19243:443
    volumes:
      - ./lbs_fidelisation_service/api:/var/www/api
      - ./lbs_fidelisation_service/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - lbs.net
    links:
#      - mongo.cat:dbcat
      - mysql.fidelisation:fidelisation

# Services de gestion des données commande

  mysql.commande:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=command
      - MYSQL_USER=command_lbs
      - MYSQL_PASSWORD=command_lbs
      - MYSQL_DATABASE=command_lbs
    ports:
      - '3317:3306'
    networks:
      - lbs.net
    volumes:
      - './lbs_commande_service/sql:/var/sql'

# Services de gestion des données catalogue

  mysql.catalogue:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=catalogue
      - MYSQL_USER=catalogue_lbs
      - MYSQL_PASSWORD=catalogue_lbs
      - MYSQL_DATABASE=catalogue_lbs
    ports:
      - '3318:3306'
    networks:
      - lbs.net
    volumes:
      - './lbs_catalogue_service/sql:/var/sql'


# Services de gestion des données fidelisation

  mysql.fidelisation:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=fidelisation
      - MYSQL_USER=fidelisation_lbs
      - MYSQL_PASSWORD=fidelisation_lbs
      - MYSQL_DATABASE=fidelisation_lbs
    ports:
      - '3319:3306'
    networks:
      - lbs.net
    volumes:
      - './lbs_fidelisation_service/sql:/var/sql'

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - lbs.net
    links:
      - mysql.commande:command
      - mysql.catalogue:catalogue
      - mysql.fidelisation:fidelisation

#
# mongo service, pour un catalogue mongo
#

#  mongo.cat:
#    image: 'mongo:latest'
#    volumes:
#      - ./lbs_catalogue_service/data:/var/data
#    working_dir: /var/data
#    networks:
#      - lbs.net
#    ports:
#      - 27018:27017
#  mongo-express:
#    image: mongo-express:latest
#    networks:
#      - lbs.net
#    ports:
#      - 8081:8081
#    links:
#      - mongo.cat:mongo